version: "3.8"

services:
  bilal:
    build:
      context: .
      dockerfile: Dockerfile
    #ports:
    #  - "8080:80"
    container_name: bilal_container
    restart: unless-stopped
    networks:
      - nginx

networks:
  nginx:
    external: true
